name: BuildFamilyHistory

on:
  workflow_dispatch:
    branches: [ master ]
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2
        with:
          repository: 'bertcarnell/CarnellRettgersFamilyHistory'
          path: ./CarnellRettgersFamilyHistory
      - name: Create Docker Network and Server
        shell: bash
        run: |
          docker network create mynetwork
          docker run -d -p 4445:4444 --name ffdocker --network mynetwork selenium/standalone-firefox:2.53.1
      - name: Download R docker container
        shell: bash
        run: |
          docker run -dit -p 4443:4442 --name crfamhist --link ffdocker --network mynetwork -v `pwd`/CarnellRettgersFamilyHistory/src:/repo --entrypoint /bin/bash bertcarnell/crfamhist
      - name: Download GEDCOM
        shell: bash
        env:
          SUPER_SECRET: ${{ secrets.ANCESTRY_PWD }}
        run: |
          docker exec crfamhist Rscript /repo/Ancestry_gedcom_download.R ffdocker 4444 "$SUPER_SECRET" /repo/carnell_rettgers.ged
      - name: Modify GEDCOM for Gramps
        shell: bash
        run: |
          docker exec crfamhist Rscript --vanilla /repo/Modify_GEDCOM.R /repo/carnell_rettgers.ged
      - name: Install Gramps
        shell: bash
        run: |
          sudo apt-get install -y gramps 
      - name: Run Test Gramps Report
        shell: bash
        run: |
          gramps -y -q -i CarnellRettgersFamilyHistory/src/carnell_rettgers.ged -a report -p "name=det_descendant_report"
      - name: Clean up
        shell: bash
        run: |
          docker kill ffdocker
          docker rm ffdocker
          docker kill crfamhist
          docker rm crfamhist
