name: BuildFamilyHistory

on:
  workflow_dispatch:
    branches: [ master ]
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2
        with:
          repository: 'bertcarnell/CarnellRettgersFamilyHistory'
          path: ./CarnellRettgersFamilyHistory
      - name: Create Docker Network and Server
        shell: bash
        run: |
          docker network create mynetwork
          docker run -d -p 4445:4444 --name ffdocker --network mynetwork selenium/standalone-firefox:2.53.1
      - name: Download R docker container
        shell: bash
        run: |
          docker run -dit -p 4443:4442 --name crfamhist --link ffdocker --network mynetwork -v `pwd`/CarnellRettgersFamilyHistory:/repo --entrypoint /bin/bash bertcarnell/crfamhist
      - name: Download GEDCOM
        shell: bash
        env:
          SUPER_SECRET: ${{ secrets.ANCESTRY_PWD }}
        run: |
          docker exec crfamhist Rscript /repo/src/Ancestry_gedcom_download.R ffdocker 4444 "$SUPER_SECRET" /repo/src/carnell_rettgers.ged
      - name: Modify GEDCOM for Gramps
        shell: bash
        run: |
          docker exec crfamhist Rscript --vanilla /repo/src/Modify_GEDCOM.R /repo/src/carnell_rettgers.ged
      - name: Install Gramps and Tex
        shell: bash
        run: |
          sudo apt-get install -y gramps rubber texlive-base texlive-fonts-recommended texlive-fonts-extra texlive-bibtex-extra texlive-extra-utils texlive-latex-extra texlive-latex-recommended texlive-xetex
      - name: Run Gramps Reports
        shell: bash
        run: |
          cd CarnellRettgersFamilyHistory/src
          make gramps OUTPUT_PATH=.. GEDCOM_FILE=carnell_rettgers.ged GEDCOM_PATH=.
          cd ../..
          ls -alh CarnellRettgersFamilyHistory/tex_input
          ls -alh CarnellRettgersFamilyHistory/tex_input_private
      - name: Modify Tex Output
        shell: bash
        run: |
          docker exec crfamhist Rscript --vanilla /repo/src/Modify_Gramps_Output.R /repo
      - name: Tex the Reports
        shell: bash
        run: |
          cd CarnellRettgersFamilyHistory/src
          make tex OUTPUT_PATH=.. GEDCOM_FILE=carnell_rettgers.ged GEDCOM_PATH=.
          cd ../..
      - name: Upload Tex results
        uses: actions/upload-artifact@master
        with:
          name: det_ancestor_reports
          path: | 
            CarnellRettgersFamilyHistory/tex_input
            CarnellRettgersFamilyHistory/tex_output
      - name: Upload PDF results
        uses: actions/upload-artifact@master
        with:
          name: pdf_reports
          path: |
            CarnellRettgersFamilyHistory/pdf_output/Volume1.pdf
            CarnellRettgersFamilyHistory/pdf_output/Volume2.pdf
            CarnellRettgersFamilyHistory/pdf_output/Volume3.pdf
            CarnellRettgersFamilyHistory/pdf_output/Volume4.pdf
            CarnellRettgersFamilyHistory/pdf_output/Volume5.pdf
      - name: Clean up
        shell: bash
        run: |
          docker kill ffdocker
          docker rm ffdocker
          docker kill crfamhist
          docker rm crfamhist
