name: BuildFamilyHistory

on:
  workflow_dispatch:
    branches: [ master ]
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Repository
        uses: actions/checkout@v2
      - name: Create Docker Network and Server
        shell: bash
        run: |
          docker network create mynetwork
          docker run -d -p 4445:4444 --name ffdocker --network mynetwork selenium/standalone-firefox:2.53.1
      - name: Download R docker container
        shell: bash
        run: |
          docker run -dit -p 4443:4442 --name crfamhist --link ffdocker --network mynetwork -v `pwd`/src:/repo --entrypoint /bin/bash bertcarnell/crfamhist
      - name: Download GEDCOM
        shell: bash
        env:
          SUPER_SECRET: ${{ secrets.ANCESTRY_PWD }}
        run: |
          # docker exec crfamhist Rscript /repo/Ancestry_gedcom_download.R ffdocker 4444 "$SUPER_SECRET"
          ls -alh
      - name: Checkout Gramps
        uses: actions/checkout@v2
        with:
          repository: 'gramps-project/gramps'
      - name: Check files
        shell: bash
        run: ls -alh

